# Dynamic configuration
# dynamic.yml

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certificates/traefik.crt
        keyFile: /etc/traefik/certificates/traefik.key
  certificates:
    - certFile: /etc/traefik/certificates/traefik.crt
      keyFile: /etc/traefik/certificates/traefik.key
      stores:
        - default
  options:
    modern:
      minVersion: VersionTLS13

http:
  routers:
    shelly:
      entryPoints:
        - "websecure"
      tls: true
      rule: "Host(`{{env "SHELLY_DOMAIN"}}`)"
      service: shelly
      middlewares:
        - https-redirect@file
        - additional-headers@file
    deluge:
      entryPoints:
        - "websecure"
      tls: true
      rule: "Host(`{{env "DELUGE_DOMAIN"}}`)"
      service: deluge
      middlewares:
        - https-redirect@file
        - additional-headers@file
  services:
    shelly:
      loadBalancer:
        servers:
          - url: "http://{{env "SHELLY_IP"}}"
        passHostHeader: false
    deluge:
      loadBalancer:
        servers:
          - url: "http://{{env "DELUGE_IP"}}"
        passHostHeader: true
  middlewares:
    additional-headers:
      headers:
        contentTypeNosniff: true
        contentSecurityPolicy: frame-src {{env "HOMEASSISTANT_DOMAIN"}}
        stsIncludeSubdomains: true
        stsSeconds: 63072000
    https-redirect:
      redirectscheme:
        scheme: https
