# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - !env_var REVERSE_PROXY_IP
    - 127.0.0.1
    - ::1
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  ip_ban_enabled: true
  login_attempts_threshold: 5
    
# Text to speech
tts:
  - platform: google_translate

homeassistant:
  customize: !include customize.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Enable custom themes
frontend:
  themes: !include_dir_merge_named themes

config_editor:

xiaomi_miot:
  # https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/device_customizes.py
  device_customizes:
    viomi.vacuum.v8:
      miot_local: true
      chunk_properties: 10

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    force_api: viomi
    draw: ['all']
    attributes:
      - calibration_points
    scan_interval:
      seconds: 10
